### PR TITLE
update an example to use tools instead of a function

### PR DESCRIPTION
**Pull request by nwatab**
- [x] I understand that this repository is auto-generated and my pull request may not be merged

## Changes being requested
Update an example of function calling while streaming to use .tool_calls. Though openai-node library now lets a user to call a function automatically, some people may want to control at lower level.

## Additional context & links
https://github.com/openai/openai-node/issues/507#issuecomment-1825010015

### CODE REVIEW

**Comment by nwatab** [comment]
I found `examples/function-call-stream-raw.ts` is the same as `examples/function-call-stream.ts`. I was not sure about the file, and so I didn't touch it.

**Comment by rattrayalex** [comment]
Thanks very much @nwatab! Can you rename the file as well?

We should remove a bunch of the old function calling examples, including the redundant `-raw.ts` one. You're welcome to do that here, or we can later.

OOC, any reason not to use `.runTools()`?

**Comment by nwatab** [comment]
Thanks for checking the PR. I renamed the file name and overwrote a commit history. I'll keep on doing when I have time.

The reason is simple. I had been writing the source code for the function call even before the release of the `.runTools` feature. I thought it would be faster to deliver to change my code to use `.tool_calls`, rather than upgrading library versions and use new feature.
Though I want to control at lower-level at some extent. I will see the specifications and behavior of `.runTools` and decide whether to use it moving forward.

**Comment by rattrayalex** [comment]
Amazing, thank you @nwatab ! I hope to review and merge tomorrow. 

I'll look forward to your feedback on `.runTools` as well!

**Review by BertsLifee — APPROVED** [review]

**Comment by rattrayalex** [comment]
This change has been incorporated on our end and will be released soon! Thank you very much.

**Pull request closed without merging**
